import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./contexts/user.js";
import ProfilePage from "./profile/page";
import { LoadingProvider } from "./contexts/loading_context";
import { PostProvider } from "./contexts/post";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">

      <body className={inter.className}>
        <LoadingProvider>
          <UserProvider>
            <PostProvider>
              {children}
            </PostProvider>
          </UserProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
