CREATE TABLE IF NOT EXISTS likes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    PostID INTEGER ,
    CommentID INTEGER,
    UserUUID VARCHAR(60),
    FOREIGN KEY (UserUUID) REFERENCES users(uuid) ON DELETE CASCADE
)